# Importing the packages

In [1]:
import time
import pandas as pd
import numpy
import matplotlib.pyplot as plt
import random
import sklearn
from random import randrange
from random import seed

# Importing dataset 

In [2]:
dataset=pd.read_csv(r'c:\Users\Rashika\Downloads\A_Z Handwritten Data.csv',encoding='UTF-8')
dataset

0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  ...  0.639  0.640  \
0        0    0    0    0    0    0    0    0    0    0  ...      0      0   
1        0    0    0    0    0    0    0    0    0    0  ...      0      0   
2        0    0    0    0    0    0    0    0    0    0  ...      0      0   
3        0    0    0    0    0    0    0    0    0    0  ...      0      0   
4        0    0    0    0    0    0    0    0    0    0  ...      0      0   
...     ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
372445  25    0    0    0    0    0    0    0    0    0  ...      0      0   
372446  25    0    0    0    0    0    0    0    0    0  ...      0      0   
372447  25    0    0    0    0    0    0    0    0    0  ...      0      0   
372448  25    0    0    0    0    0    0    0    0    0  ...      0      0   
372449  25    0    0    0    0    0    0    0    0    0  ...      0      0   

        0.641  0.642  0.643  0.644  0.645  0.646  0.647  0.648  
0           0      0      0      0      0      0      0      0  
1           0      0      0      0      0      0      0      0  
2           0      0      0      0      0      0      0      0  
3           0      0      0      0      0      0      0      0  
4           0      0      0      0      0      0      0      0  
...       ...    ...    ...    ...    ...    ...    ...    ...  
372445      0      0      0      0      0      0      0      0  
372446      0      0      0      0      0      0      0      0  
372447      0      0      0      0      0      0      0      0  
372448      0      0      0      0      0      0      0      0  
372449      0      0      0      0      0      0      0      0  

[372450 rows x 785 columns]

In [3]:
dataset.columns=list(range(785))
dataset.head()

0    1    2    3    4    5    6    7    8    9    ...  775  776  777  778  \
0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
1    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
2    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
3    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

   779  780  781  782  783  784  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 785 columns]

In [4]:
X=[]
Y=[]
for index,row in dataset.iterrows():
        Y.append(row[0])
        X.append(row[1:])

In [5]:
arr=[i for i in range(3)]
print(arr)


[0, 1, 2]


In [6]:
for i in range(3):
    n=random.randint(0,len(X))
    arr[i]=n
print(arr)

[120839, 273772, 161645]


In [7]:
x = numpy.reshape(X, (-1, 784))#-1 auto adjusts array shape 

In [8]:
x.shape

(372450, 784)

# Dividing dataset into train and test dataset

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,Y,test_size=0.1,random_state=0)

In [10]:
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [11]:
x_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
y_train

[14,
 24,
 16,
 18,
 2,
 25,
 23,
 14,
 2,
 20,
 17,
 22,
 0,
 18,
 19,
 14,
 2,
 0,
 15,
 19,
 14,
 2,
 15,
 0,
 15,
 14,
 14,
 3,
 20,
 20,
 3,
 13,
 11,
 11,
 14,
 23,
 2,
 21,
 18,
 2,
 4,
 14,
 0,
 20,
 14,
 14,
 1,
 17,
 9,
 23,
 18,
 3,
 14,
 15,
 11,
 17,
 3,
 15,
 0,
 0,
 16,
 20,
 20,
 20,
 11,
 1,
 18,
 14,
 0,
 18,
 19,
 17,
 18,
 24,
 4,
 2,
 3,
 18,
 4,
 11,
 14,
 25,
 6,
 20,
 24,
 1,
 3,
 2,
 2,
 14,
 14,
 13,
 19,
 21,
 4,
 17,
 18,
 19,
 18,
 19,
 14,
 15,
 14,
 19,
 19,
 18,
 19,
 20,
 14,
 18,
 12,
 18,
 0,
 14,
 23,
 14,
 6,
 12,
 14,
 22,
 4,
 14,
 12,
 2,
 18,
 19,
 12,
 16,
 7,
 20,
 25,
 13,
 4,
 18,
 14,
 18,
 4,
 14,
 22,
 0,
 1,
 10,
 19,
 22,
 17,
 0,
 24,
 0,
 20,
 20,
 20,
 14,
 19,
 14,
 19,
 10,
 15,
 11,
 17,
 19,
 18,
 19,
 15,
 12,
 14,
 18,
 15,
 20,
 3,
 18,
 14,
 18,
 19,
 18,
 13,
 1,
 21,
 14,
 3,
 14,
 18,
 13,
 14,
 14,
 25,
 13,
 14,
 14,
 20,
 7,
 17,
 20,
 18,
 18,
 16,
 18,
 23,
 14,
 19,
 14,
 18,
 14,
 20,
 18,
 16,
 20,
 14,
 24,
 18,
 

In [13]:
y_test

[24,
 14,
 4,
 18,
 17,
 14,
 18,
 19,
 12,
 16,
 12,
 19,
 15,
 11,
 14,
 19,
 13,
 2,
 18,
 20,
 13,
 13,
 10,
 19,
 18,
 18,
 2,
 8,
 18,
 24,
 2,
 14,
 24,
 14,
 3,
 15,
 17,
 25,
 20,
 20,
 17,
 10,
 17,
 18,
 23,
 3,
 14,
 15,
 19,
 23,
 15,
 11,
 17,
 22,
 24,
 19,
 19,
 15,
 6,
 20,
 17,
 12,
 10,
 18,
 18,
 4,
 3,
 11,
 7,
 12,
 13,
 2,
 7,
 14,
 18,
 25,
 18,
 20,
 18,
 19,
 18,
 19,
 3,
 20,
 14,
 3,
 18,
 0,
 6,
 3,
 20,
 9,
 9,
 15,
 2,
 16,
 19,
 2,
 22,
 18,
 14,
 19,
 14,
 13,
 15,
 14,
 15,
 14,
 22,
 16,
 4,
 20,
 4,
 20,
 18,
 2,
 14,
 17,
 14,
 17,
 16,
 11,
 16,
 13,
 6,
 18,
 19,
 14,
 18,
 6,
 11,
 6,
 18,
 18,
 20,
 15,
 13,
 19,
 14,
 24,
 17,
 3,
 14,
 14,
 20,
 20,
 4,
 23,
 10,
 4,
 14,
 15,
 14,
 14,
 14,
 19,
 17,
 18,
 3,
 23,
 18,
 3,
 20,
 13,
 12,
 18,
 15,
 14,
 14,
 3,
 21,
 0,
 14,
 19,
 24,
 24,
 23,
 8,
 12,
 0,
 10,
 2,
 14,
 14,
 9,
 12,
 25,
 13,
 14,
 13,
 4,
 5,
 10,
 4,
 15,
 2,
 4,
 18,
 13,
 24,
 14,
 14,
 2,
 23,
 2,
 12,
 2,
 18,
 23,
 9

# Calculating prior probabilities

In [14]:
Y_classtotal=26
county=numpy.zeros(Y_classtotal)#initialize 1-D county array with zeros
county

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
Y_classtotal=26
county=numpy.zeros(Y_classtotal)#initialize 1-D county array with zeros
county

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
lenofy_train=len(y_train)
lenofy_train

335205

In [17]:
for i in y_train:
    county[i]+=1
    

In [18]:
county

array([12495.,  7841., 21037.,  9136., 10267.,  1054.,  5169.,  6496.,
        1000.,  7615.,  5095., 10384., 11106., 17058., 51967., 17380.,
        5175., 10435., 43610., 20261., 26171.,  3790.,  9729.,  5663.,
        9822.,  5449.])

In [19]:
prior=county/lenofy_train #prior probablities of each classes[0-25]
prior

array([0.0372757 , 0.02339166, 0.06275861, 0.02725496, 0.03062902,
       0.00314434, 0.01542041, 0.01937919, 0.00298325, 0.02271744,
       0.01519965, 0.03097806, 0.03313196, 0.05088826, 0.1550305 ,
       0.05184887, 0.01543831, 0.0311302 , 0.13009949, 0.06044361,
       0.07807461, 0.01130651, 0.02902403, 0.01689414, 0.02930147,
       0.01625572])

In [20]:
x_train[i]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  36, 117, 198, 198, 19

# Calculate class conditional probability

In [21]:
noofcols=784
a=128
b=int(256/a)

f0=numpy.ones(Y_classtotal*noofcols).reshape(Y_classtotal,noofcols)

f1=numpy.ones(Y_classtotal*noofcols).reshape(Y_classtotal,noofcols)


# scaling pixels value 
pixel value 0-127 scaled as 0
pixel value 128-255 scaled as 1


In [22]:
size=784
print(size)
for i in range(len(x_train)):
    for j in range(len(x_train[i])):
        a=x_train[i][j]
        if((a>128)):
            x_train[i][j]=1
        else:
            x_train[i][j]=0

784


In [23]:
x_train.shape

(335205, 784)

In [24]:
x_train[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,

In [25]:
x1 = numpy.reshape(x_train, (-1,335205 ))#transposing array

In [26]:
x1.shape

(784, 335205)

# #calculating probability of 0th pixel being equal to zero given class is equal to zero. likewise calculating probability each pixel being equal to zero given a class

In [27]:
for i in range(len(x_train)):
    classofy=y_train[i]
    for j in range(784):
        if(x_train[i][j]==0):
            f0[classofy][j]+=1
        else:
            f1[classofy][j]+=1

In [28]:
f0[0]

array([12496., 12496., 12496., 12496., 12496., 12496., 12496., 12496.,
       12496., 12496., 12496., 12496., 12496., 12496., 12496., 12496.,
       12496., 12496., 12496., 12496., 12496., 12496., 12496., 12496.,
       12496., 12496., 12496., 12496., 12496., 12496., 12496., 12496.,
       12496., 12496., 12496., 12496., 12496., 12496., 12496., 12496.,
       12496., 12496., 12496., 12496., 12496., 12496., 12496., 12496.,
       12496., 12496., 12496., 12496., 12496., 12496., 12496., 12496.,
       12496., 12496., 12496., 12496., 12496., 12496., 12496., 12496.,
       12496., 12496., 12496., 12496., 12496., 12496., 12496., 12495.,
       12495., 12496., 12496., 12496., 12496., 12495., 12495., 12496.,
       12496., 12496., 12496., 12496., 12496., 12496., 12496., 12496.,
       12496., 12496., 12496., 12496., 12496., 12496., 12495., 12495.,
       12496., 12496., 12495., 12494., 12494., 12495., 12495., 12494.,
       12495., 12495., 12495., 12495., 12496., 12496., 12496., 12496.,
      

In [29]:
f1[0]

array([1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 2.000e+00,
       2.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 2.000e+00,
       2.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 

In [30]:
for i in range(26):
    f0[i]=f0[i]/county[i]
    f1[i]=f1[i]/county[i]

In [31]:
f0[0]

array([1.00008003, 1.00008003, 1.00008003, 1.00008003, 1.00008003,
       1.00008003, 1.00008003, 1.00008003, 1.00008003, 1.00008003,
       1.00008003, 1.00008003, 1.00008003, 1.00008003, 1.00008003,
       1.00008003, 1.00008003, 1.00008003, 1.00008003, 1.00008003,
       1.00008003, 1.00008003, 1.00008003, 1.00008003, 1.00008003,
       1.00008003, 1.00008003, 1.00008003, 1.00008003, 1.00008003,
       1.00008003, 1.00008003, 1.00008003, 1.00008003, 1.00008003,
       1.00008003, 1.00008003, 1.00008003, 1.00008003, 1.00008003,
       1.00008003, 1.00008003, 1.00008003, 1.00008003, 1.00008003,
       1.00008003, 1.00008003, 1.00008003, 1.00008003, 1.00008003,
       1.00008003, 1.00008003, 1.00008003, 1.00008003, 1.00008003,
       1.00008003, 1.00008003, 1.00008003, 1.00008003, 1.00008003,
       1.00008003, 1.00008003, 1.00008003, 1.00008003, 1.00008003,
       1.00008003, 1.00008003, 1.00008003, 1.00008003, 1.00008003,
       1.00008003, 1.        , 1.        , 1.00008003, 1.00008

In [33]:
county[0]

12495.0

In [34]:
len(x_test)

37245

In [35]:
import math 

In [39]:
count_correct_prediction=0  
count_total_prediction=0
for i in range(len(x_test)):
    d=x_test[i]
    q = numpy.zeros(26)
    for j in range(784):
        if(d[j]==0):
            for k in range(26):
                q[k]+=math.log(f0[k][j])
        else:
            for k in range(26):
                q[k]+=math.log(f1[k][j])
                
    for l in range(26):
        q[l]=q[l]+prior[l]
        
    max=q[0]
    y_predictedvalue=0
    for m in range(26):
        if((q[m]>max)):
            max=q[m]
            y_predictedvalue=m
    y_actualvalue=y_test[i]
    


    if((y_predictedvalue == y_actualvalue)):
        count_correct_prediction=count_correct_prediction+1
    
    count_total_prediction+=1
    
accuracy =  (count_correct_prediction/count_total_prediction)*100        

In [40]:
print(count_correct_prediction)

24931


In [41]:
len(x_test)

37245

In [42]:
print(accuracy)

66.93784400590684
